import { IProductType } from "../../types/enum";
import { ISubscription } from "../../types/subscription";

export const FAKE_CARDS: ISubscription[] = [
  {
    id: "1",
    userId: "US1",
    parkingZoneId: "1",
    parkingLocationId: "1",
    productType: IProductType.Tenant,
    startDate: new Date("2023-01-01"),
    endDate: new Date("2024-12-31"),
    subscriptionFee: 35,
    clampingFee: 10,
    changeSignageFee: 20,
    isPaid: true,
    licensePlate: "ABC123",
    paymentDate: new Date("2023-01-01"),
  },
  {
    id: "2",
    userId: "US1",
    parkingZoneId: "2",
    parkingLocationId: "2",
    productType: IProductType.Tenant,
    startDate: new Date("2023-02-01"),
    endDate: new Date("2024-01-31"),
    subscriptionFee: 35,
    clampingFee: 10,
    changeSignageFee: 25,
    isPaid: false,
    licensePlate: "ABC123",
  },
  {
    id: "3",
    userId: "US1",
    parkingZoneId: "3",
    parkingLocationId: "3",
    productType: IProductType.NonTenant,
    startDate: new Date("2023-03-01"),
    endDate: new Date("2023-03-07"),
    subscriptionFee: 35,
    clampingFee: 10,
    changeSignageFee: 15,
    isPaid: true,
    licensePlate: "ABC123",
    paymentDate: new Date("2023-03-01"),
  },
  {
    id: "4",
    userId: "US1",
    parkingZoneId: "1",
    parkingLocationId: "1",
    productType: IProductType.NonTenant,
    startDate: new Date("2024-04-01"),
    endDate: new Date("2025-04-01"),
    subscriptionFee: 35,
    clampingFee: 10,
    changeSignageFee: 10,
    isPaid: true,
    licensePlate: "ABC123",
    paymentDate: new Date("2024-04-01"),
  },
  {
    id: "5",
    userId: "US1",
    parkingZoneId: "2",
    parkingLocationId: "2",
    productType: IProductType.Tenant,
    startDate: new Date("2023-05-01"),
    endDate: new Date("2024-05-01"),
    subscriptionFee: 40,
    clampingFee: 15,
    changeSignageFee: 20,
    isPaid: false,
    licensePlate: "DEF456",
  },
  {
    id: "6",
    userId: "US1",
    parkingZoneId: "3",
    parkingLocationId: "3",
    productType: IProductType.NonTenant,
    startDate: new Date("2023-06-01"),
    endDate: new Date("2023-06-30"),
    subscriptionFee: 30,
    clampingFee: 10,
    changeSignageFee: 25,
    isPaid: true,
    licensePlate: "GHI789",
    paymentDate: new Date("2023-06-01"),
  },
  {
    id: "7",
    userId: "US1",
    parkingZoneId: "1",
    parkingLocationId: "1",
    productType: IProductType.Tenant,
    startDate: new Date("2023-07-01"),
    endDate: new Date("2024-07-01"),
    subscriptionFee: 35,
    clampingFee: 10,
    changeSignageFee: 20,
    isPaid: true,
    licensePlate: "JKL012",
    paymentDate: new Date("2023-07-01"),
  },
  {
    id: "8",
    userId: "US1",
    parkingZoneId: "2",
    parkingLocationId: "2",
    productType: IProductType.NonTenant,
    startDate: new Date("2023-08-01"),
    endDate: new Date("2023-08-31"),
    subscriptionFee: 25,
    clampingFee: 5,
    changeSignageFee: 15,
    isPaid: false,
    licensePlate: "MNO345",
  },
  {
    id: "9",
    userId: "US1",
    parkingZoneId: "3",
    parkingLocationId: "3",
    productType: IProductType.Tenant,
    startDate: new Date("2023-09-01"),
    endDate: new Date("2024-09-01"),
    subscriptionFee: 45,
    clampingFee: 20,
    changeSignageFee: 30,
    isPaid: true,
    licensePlate: "PQR678",
    paymentDate: new Date("2023-09-01"),
  },
  {
    id: "10",
    userId: "US1",
    parkingZoneId: "1",
    parkingLocationId: "1",
    productType: IProductType.NonTenant,
    startDate: new Date("2023-10-01"),
    endDate: new Date("2023-10-31"),
    subscriptionFee: 20,
    clampingFee: 5,
    changeSignageFee: 10,
    isPaid: false,
    licensePlate: "STU901",
  },
  {
    id: "11",
    userId: "US1",
    parkingZoneId: "2",
    parkingLocationId: "2",
    productType: IProductType.Tenant,
    startDate: new Date("2023-11-01"),
    endDate: new Date("2024-11-01"),
    subscriptionFee: 50,
    clampingFee: 25,
    changeSignageFee: 35,
    isPaid: true,
    licensePlate: "VWX234",
    paymentDate: new Date("2023-11-01"),
  },
  {
    id: "12",
    userId: "US1",
    parkingZoneId: "3",
    parkingLocationId: "3",
    productType: IProductType.NonTenant,
    startDate: new Date("2023-12-01"),
    endDate: new Date("2023-12-31"),
    subscriptionFee: 15,
    clampingFee: 5,
    changeSignageFee: 10,
    isPaid: false,
    licensePlate: "YZA567",
  },
  {
    id: "13",
    userId: "US1",
    parkingZoneId: "1",
    parkingLocationId: "1",
    productType: IProductType.Tenant,
    startDate: new Date("2024-01-01"),
    endDate: new Date("2025-01-01"),
    subscriptionFee: 55,
    clampingFee: 30,
    changeSignageFee: 40,
    isPaid: true,
    licensePlate: "BCD890",
    paymentDate: new Date("2024-01-01"),
  },
  {
    id: "14",
    userId: "US1",
    parkingZoneId: "2",
    parkingLocationId: "2",
    productType: IProductType.NonTenant,
    startDate: new Date("2024-02-01"),
    endDate: new Date("2024-02-28"),
    subscriptionFee: 25,
    clampingFee: 10,
    changeSignageFee: 15,
    isPaid: false,
    licensePlate: "EFG123",
  },
  {
    id: "15",
    userId: "US1",
    parkingZoneId: "3",
    parkingLocationId: "3",
    productType: IProductType.Tenant,
    startDate: new Date("2024-03-01"),
    endDate: new Date("2025-03-01"),
    subscriptionFee: 60,
    clampingFee: 35,
    changeSignageFee: 45,
    isPaid: true,
    licensePlate: "HIJ456",
    paymentDate: new Date("2024-03-01"),
  },
  {
    id: "16",
    userId: "US1",
    parkingZoneId: "1",
    parkingLocationId: "1",
    productType: IProductType.NonTenant,
    startDate: new Date("2024-04-01"),
    endDate: new Date("2024-04-30"),
    subscriptionFee: 20,
    clampingFee: 5,
    changeSignageFee: 10,
    isPaid: false,
    licensePlate: "KLM789",
  },
  {
    id: "17",
    userId: "US1",
    parkingZoneId: "2",
    parkingLocationId: "2",
    productType: IProductType.Tenant,
    startDate: new Date("2024-05-01"),
    endDate: new Date("2025-05-01"),
    subscriptionFee: 65,
    clampingFee: 40,
    changeSignageFee: 50,
    isPaid: true,
    licensePlate: "NOP012",
    paymentDate: new Date("2024-05-01"),
  },
  {
    id: "18",
    userId: "US1",
    parkingZoneId: "3",
    parkingLocationId: "3",
    productType: IProductType.NonTenant,
    startDate: new Date("2024-06-01"),
    endDate: new Date("2024-06-30"),
    subscriptionFee: 25,
    clampingFee: 10,
    changeSignageFee: 15,
    isPaid: false,
    licensePlate: "QRS345",
  },
  {
    id: "19",
    userId: "US1",
    parkingZoneId: "1",
    parkingLocationId: "1",
    productType: IProductType.Tenant,
    startDate: new Date("2024-07-01"),
    endDate: new Date("2025-07-01"),
    subscriptionFee: 70,
    clampingFee: 45,
    changeSignageFee: 55,
    isPaid: true,
    licensePlate: "TUV678",
    paymentDate: new Date("2024-07-01"),
  },
  {
    id: "20",
    userId: "US1",
    parkingZoneId: "2",
    parkingLocationId: "2",
    productType: IProductType.NonTenant,
    startDate: new Date("2024-08-01"),
    endDate: new Date("2024-08-31"),
    subscriptionFee: 30,
    clampingFee: 15,
    changeSignageFee: 20,
    isPaid: false,
    licensePlate: "WXY901",
  },
  {
    id: "21",
    userId: "US1",
    parkingZoneId: "3",
    parkingLocationId: "3",
    productType: IProductType.Tenant,
    startDate: new Date("2024-09-01"),
    endDate: new Date("2025-09-01"),
    subscriptionFee: 75,
    clampingFee: 50,
    changeSignageFee: 60,
    isPaid: true,
    licensePlate: "ZAB234",
    paymentDate: new Date("2024-09-01"),
  },
  {
    id: "22",
    userId: "US1",
    parkingZoneId: "1",
    parkingLocationId: "1",
    productType: IProductType.NonTenant,
    startDate: new Date("2024-10-01"),
    endDate: new Date("2024-10-31"),
    subscriptionFee: 35,
    clampingFee: 20,
    changeSignageFee: 25,
    isPaid: false,
    licensePlate: "CDE567",
  },
  {
    id: "23",
    userId: "US1",
    parkingZoneId: "2",
    parkingLocationId: "2",
    productType: IProductType.Tenant,
    startDate: new Date("2024-11-01"),
    endDate: new Date("2025-11-01"),
    subscriptionFee: 80,
    clampingFee: 55,
    changeSignageFee: 65,
    isPaid: true,
    licensePlate: "FGH890",
    paymentDate: new Date("2024-11-01"),
  },
  {
    id: "24",
    userId: "US1",
    parkingZoneId: "3",
    parkingLocationId: "3",
    productType: IProductType.NonTenant,
    startDate: new Date("2024-12-01"),
    endDate: new Date("2024-12-31"),
    subscriptionFee: 40,
    clampingFee: 25,
    changeSignageFee: 30,
    isPaid: false,
    licensePlate: "IJK123",
  },
  {
    id: "25",
    userId: "US1",
    parkingZoneId: "1",
    parkingLocationId: "1",
    productType: IProductType.Tenant,
    startDate: new Date("2025-01-01"),
    endDate: new Date("2026-01-01"),
    subscriptionFee: 85,
    clampingFee: 60,
    changeSignageFee: 70,
    isPaid: true,
    licensePlate: "LMN456",
    paymentDate: new Date("2025-01-01"),
  },
  {
    id: "26",
    userId: "US1",
    parkingZoneId: "2",
    parkingLocationId: "2",
    productType: IProductType.NonTenant,
    startDate: new Date("2025-02-01"),
    endDate: new Date("2025-02-28"),
    subscriptionFee: 45,
    clampingFee: 30,
    changeSignageFee: 35,
    isPaid: false,
    licensePlate: "OPQ789",
  },
  {
    id: "27",
    userId: "US1",
    parkingZoneId: "3",
    parkingLocationId: "3",
    productType: IProductType.Tenant,
    startDate: new Date("2025-03-01"),
    endDate: new Date("2026-03-01"),
    subscriptionFee: 90,
    clampingFee: 65,
    changeSignageFee: 75,
    isPaid: true,
    licensePlate: "RST012",
    paymentDate: new Date("2025-03-01"),
  },
  {
    id: "28",
    userId: "US1",
    parkingZoneId: "1",
    parkingLocationId: "1",
    productType: IProductType.NonTenant,
    startDate: new Date("2025-04-01"),
    endDate: new Date("2025-04-30"),
    subscriptionFee: 50,
    clampingFee: 35,
    changeSignageFee: 40,
    isPaid: false,
    licensePlate: "UVW345",
  },
  {
    id: "29",
    userId: "US1",
    parkingZoneId: "2",
    parkingLocationId: "2",
    productType: IProductType.Tenant,
    startDate: new Date("2025-05-01"),
    endDate: new Date("2026-05-01"),
    subscriptionFee: 95,
    clampingFee: 70,
    changeSignageFee: 80,
    isPaid: true,
    licensePlate: "XYZ678",
    paymentDate: new Date("2025-05-01"),
  },
  {
    id: "30",
    userId: "US1",
    parkingZoneId: "3",
    parkingLocationId: "3",
    productType: IProductType.NonTenant,
    startDate: new Date("2025-06-01"),
    endDate: new Date("2025-06-30"),
    subscriptionFee: 55,
    clampingFee: 40,
    changeSignageFee: 45,
    isPaid: false,
    licensePlate: "ABC901",
  },
  {
    id: "31",
    userId: "US1",
    parkingZoneId: "1",
    parkingLocationId: "1",
    productType: IProductType.Tenant,
    startDate: new Date("2025-07-01"),
    endDate: new Date("2026-07-01"),
    subscriptionFee: 100,
    clampingFee: 75,
    changeSignageFee: 85,
    isPaid: true,
    licensePlate: "DEF234",
    paymentDate: new Date("2025-07-01"),
  },
  {
    id: "32",
    userId: "US1",
    parkingZoneId: "2",
    parkingLocationId: "2",
    productType: IProductType.NonTenant,
    startDate: new Date("2025-08-01"),
    endDate: new Date("2025-08-31"),
    subscriptionFee: 60,
    clampingFee: 45,
    changeSignageFee: 50,
    isPaid: false,
    licensePlate: "GHI567",
  },
  {
    id: "33",
    userId: "US1",
    parkingZoneId: "3",
    parkingLocationId: "3",
    productType: IProductType.Tenant,
    startDate: new Date("2025-09-01"),
    endDate: new Date("2026-09-01"),
    subscriptionFee: 105,
    clampingFee: 80,
    changeSignageFee: 90,
    isPaid: true,
    licensePlate: "JKL890",
    paymentDate: new Date("2025-09-01"),
  },
  {
    id: "34",
    userId: "US1",
    parkingZoneId: "1",
    parkingLocationId: "1",
    productType: IProductType.NonTenant,
    startDate: new Date("2025-10-01"),
    endDate: new Date("2025-10-31"),
    subscriptionFee: 65,
    clampingFee: 50,
    changeSignageFee: 55,
    isPaid: false,
    licensePlate: "MNO123",
  },
];
