import { IProductType } from "../../types/enum.d.ts";
import { ISubscription } from "../../types/subscription";

export const FAKE_CARDS: ISubscription[] = [
  {
    id: "1",
    userId: "US1",
    parkingZoneId: "1",
    parkingLocationId: "1",
    productType: IProductType.Tenant,
    startDate: new Date("2023-01-01"),
    endDate: new Date("2024-12-31"),
    clampingFee: 50,
    changeSignageFee: 20,
    isPaid: true,
    licensePlate: "ABC123",
  },
  {
    id: "2",
    userId: "US1",
    parkingZoneId: "2",
    parkingLocationId: "2",
    productType: IProductType.Tenant,
    startDate: new Date("2023-02-01"),
    endDate: new Date("2024-01-31"),
    clampingFee: 60,
    changeSignageFee: 25,
    isPaid: false,
    licensePlate: "ABC123",
  },
  {
    id: "3",
    userId: "US1",
    parkingZoneId: "3",
    parkingLocationId: "3",
    productType: IProductType.NonTenant,
    startDate: new Date("2023-03-01"),
    endDate: new Date("2023-03-07"),
    clampingFee: 40,
    changeSignageFee: 15,
    isPaid: true,
    licensePlate: "ABC123",
  },
  {
    id: "4",
    userId: "US1",
    parkingZoneId: "1",
    parkingLocationId: "1",
    productType: IProductType.NonTenant,
    startDate: new Date("2024-04-01"),
    endDate: new Date("2025-04-01"),
    clampingFee: 30,
    changeSignageFee: 10,
    isPaid: true,
    licensePlate: "ABC123",
  },
];
